Uber/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appUber.urls')),
    path('contas/', include('accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUp, Profile, Up_Service, Del_Servico, RegisterView
from django.urls import path, include

from django.conf.urls.static import static



urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    
    path('profile', Profile.as_view(), name='profile'),
    path('<int:pk>/Up_Servico/', Up_Service.as_view(), name='up_servico'),
    path('<int:pk>/delete/', Del_Servico.as_view(), name='del_servico'),
]

accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):
    
    Tipo_de_user = (
          ('usuario', 'usuario'),
          ('colaborador', 'colaborador')
      )
    
    veículos = (
        ('moto', 'moto'),
        ('carro', 'carro'),
        ('caminhão', 'caminhão'),
        ('carreta', 'carreta')
    )

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    tipo = models.CharField(
        'tipo_de_usuario', choices=Tipo_de_user, max_length=20, default='usuario')
    veículo = models.CharField(
        'veículo', choices=veículos, max_length=20, default='')
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    image = models.ImageField(
        'image', upload_to='user', blank=True, null=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]
    
    def to_dict(self):
        return{
            'username': self.username,
            'name': self.name,
            'email': self.email
        }

accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'tipo', 'veículo']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name',
                  'image', 'is_active', 'is_staff']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'image', 'name']

accounts/views.py
from appUber.models import Servicos, Sol_Servicos

from django.contrib.auth.models import User, Group
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .forms import UserAdminCreationForm
from django.urls import reverse_lazy


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

    #Adcionando grupo ao usuario criado
    def form_valid(self, form):
        grupo = get_object_or_404(Group, name='Usuario')

        url = super().form_valid(form)
        self.object.groups.add(grupo)
        self.object.save()
        return url

# Adcionando grupo ao colaborador criado


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('login')
    



class Profile(ListView):
    model = Sol_Servicos
    context_object_name = 'servicos'
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('profile')
   
    def get_context_data(self, *args, **kwargs):
        context = super(Profile, self).get_context_data(*args, **kwargs)
        user = self.request.user
        veiculo = user.veículo
        context['veiculo'] = Sol_Servicos.objects.all().filter(
            veiculo=veiculo)
        context['total'] = Sol_Servicos.objects.all().count()
        context['pending'] = Sol_Servicos.objects.all().filter(
            status='Pending')
        return context


class Up_Service(UpdateView):
    template_name_suffix = "_update_form"
    model = Sol_Servicos
    context_object_name = 'servicos'
    template_name = 'accounts/update.html'
    fields = ['servicos', 'coleta', 'entrega', 'time',
              'distancia',  'veiculo', 'valor', 'status']
    success_url = reverse_lazy('profile')


class Del_Servico(DeleteView):
    template_name_suffix = "_confirm_delete"
    context_object_name = 'servicos'
    model = Sol_Servicos
    template_name = 'accounts/update.html'
    success_url = reverse_lazy('profile')

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="col-sm">
            <a href="#" class="navbar-brand flex-grow-1" style="text-align: center ">
                &nbsp;&nbsp; Notifications
            </a>
        </div>
        <!-- Botões de notificação -->

        <div class="col-sm">
            <a href="#" class="text-light" id="btn-nav">
                <i class="fa-solid fa-bell"></i>
                <span class="pending">{{pending.count}}</span>
            </a>
            <a href="#" class="text-light" id="btn-nav">
                <i class="fa-solid fa-envelope"></i>
                <span class="total">{{total}}</span>
            </a>
        </div>
    </nav>
</header>
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"> <a class="navbar-brand" href="{% url 'index' %}">
                                <h3>Home</h3>
                            </a></li>
                        <!-- <li class="breadcrumb-item"><a href="#">User</a></li>
                        <li class="breadcrumb-item active" aria-current="page">User Profile</li> -->
                    </ol>
                </nav>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
                            alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                        <h5 class="my-3">{{user}}</h5>
                        <p class="text-muted mb-1">{{user.tipo}}</p>
                        <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
                        <div class="d-flex justify-content-center mb-2">
                            <button type="button" class="btn btn-primary">Follow</button>
                            <button type="button" class="btn btn-outline-primary ms-1">Message</button>
                        </div>
                    </div>
                </div>

                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.get_full_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.email}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Veículo</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.veículo}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Mobile</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">(098) 765-4321</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Address</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col-lg-8">

                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Servicos</th>
                            <th scope="col">veiculo</th>
                            <th scope="col">Percurso</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Time</th>
                            <th scope="col">Status</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for i in veiculo %}
                        {% if user.tipo == 'colaborador' %}

                        <tr>
                            <th scope="row">{{i.id}}</th>
                            <td><a href="{% url 'up_servico' i.id %}">{{i.servicos}}</a></td>
                            <td>{{i.veiculo}}</td>
                            <td>{{i.distancia}} m</td>
                            <td>{{i.valor}}</td>
                            <td>{{i.time}}</td>
                            <td>{{i.status}}</td>
                        </tr>
                        
                        {%endif%}
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>





{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}

<div class="container">
    <div class="row">

        <div class="col-sm-12 col-lg-4">
        </div>

        <div class="col-sm-12 col-lg-4 login">
            <div class="form form-control login">
                <!-- <form class="form-signin" method="post" autocomplete="off">
                    {% csrf_token %}
                    <h2 class="card-title text-center">Si</h2>
                    <input type="hidden" name="next" value="{{next}}">
                  //{% bootstrap_form form %} 

                    <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                    <br>
                  Register buttons
                    <div class="text-center">

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="lni lni-linkedin-original"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="lni lni-github-original"></i>
                        </button>

                    </div>
                </form> -->
                <form class="form-signin register" method="post" autocomplete="off">
                    {% csrf_token %}
                    <h2 class="card-title text-center">Signup</h2>
                    <input type="hidden" name="next" value="">
                    <div class="mb-3">
                        <label class="form-label" for="id_username">Apelido / Usuário</label><input type="text"
                            name="username" maxlength="30" autofocus="" class="form-control"
                            placeholder="Apelido / Usuário" required="" id="id_username">
                        <div class="form-text">Um nome curto que será usado para identificá-lo de forma única na
                            plataforma</div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_email">E-mail</label><input type="email" name="email"
                            maxlength="254" class="form-control" placeholder="E-mail" required="" id="id_email">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_tipo">Tipo_de_usuario</label>
                        <select name="tipo" class="form-select" id="id_tipo" onclick="Veiculo()">
                            <option value="usuario" selected="">usuario</option>

                            <option value="colaborador">colaborador</option>

                        </select>
                    </div>
                    <div class="mb-3" id="veiculo_none">
                        <label class="form-label" for="id_veículo">Veículo</label>
                        <select name="veículo" class="form-select" id="id_veículo">


                            <option value="" selected="">---------</option>

                            <option value="moto">moto</option>

                            <option value="carro">carro</option>

                            <option value="caminhão">caminhão</option>

                            <option value="carreta">carreta</option>

                        </select>
                    </div>
                    <div class="mb-3"><label class="form-label" for="id_password1">Senha</label><input type="password"
                            name="password1" autocomplete="new-password" class="form-control" placeholder="Senha"
                            required="" id="id_password1">
                        <div class="form-text">
                            <ul>
                                <li>Sua senha não pode ser muito parecida com o resto das suas informações pessoais.
                                </li>
                                <li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                                <li>Sua senha não pode ser uma senha comumente utilizada.</li>
                                <li>Sua senha não pode ser inteiramente numérica.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="mb-3"><label class="form-label" for="id_password2">Confirmação de senha</label><input
                            type="password" name="password2" autocomplete="new-password" class="form-control"
                            placeholder="Confirmação de senha" required="" id="id_password2">
                        <div class="form-text">Informe a mesma senha informada anteriormente, para verificação.</div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                    <br>
                    <!-- Register buttons -->
                    <div class="text-center">

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="lni lni-linkedin-original"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="lni lni-github-original"></i>
                        </button>

                    </div>
                </form>

            </div>

        </div>
        <div class="col-sm-12 col-lg-4">
        </div>
    </div>
</div>


{% endblock %}

<div class="form-row field-veículo">


    <div>


        <label for="id_veículo">Veículo:</label>

        <select name="veículo" id="id_veículo">
            <option value="" selected="">---------</option>

            <option value="moto">moto</option>

            <option value="carro">carro</option>

            <option value="caminhão">caminhão</option>

            <option value="carreta">carreta</option>

        </select>



    </div>

</div>

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default justify-content-end">
            <div class="nav">
                <a class="navbar-brand" href="{% url 'profile' %}">Profile</a>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <h3>Serviços</h3>
                </div>
                <div class="offset-6 col-2">
                    <h3>Actions</h3>
                </div>
            </div>
        </div>
        <br><br>
        <div class="col-4">
            <form id="my-form" action="#" method="POST" class="form" autocomplete="off"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}

            </form> 

            
        </div>
        <div class="offset-6 col-2">

            <div class="form-group">
                <button form="my-form" type="submit" class="btn btn-secondary">Update</button>
            </div>
            <br>

            <div class="form-group">
                <a href="{% url 'del_servico' pk=servicos.id %}" form="my-form" type="submit"
                    class="btn btn-danger">Delete</a>
            </div>


        </div>


        <!-- {% if messages %}
        {%for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{message}}
        </div>
        {%endfor%}
        {% endif %} -->

    </div>
</div>
{% endblock %}