Uber/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appUber.urls')),
    path('contas/', include('accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appUber/urls.py
from django.urls import path
from .views import Index, Servico, Solicite
from django.urls import path, include

from django.conf.urls.static import static


urlpatterns = [
    path('', Index, name='index'),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('servicos', Servico, name='servicos'),
    path('Solicite', Solicite.as_view(), name='Solicite'),
    # path('profile', Profile, name='profile'),
    # path('editar/<int:id>', Editar, name='editar'),
    # path('editar/delete/<int:id>', Delete, name='delete')

]

appUber/models.py
from django.db import models

from django.contrib.auth import get_user_model

VEICULO = [
    ('moto', 'moto'),
    ('carro', 'carro'),
    ('caminhao', 'caminhão'),
    ('carreta', 'carreta')
]

SERVICOS = [('viagem', 'viagem'),
            ('delivery', 'delivery')
            ]

STATUS = [
    ('Waiting', 'Waiting'),
    ('Pending', 'Pending'),
    ('Accepted', 'Accepted')
]

# modelo de entrada de dados de serviço
class Servicos(models.Model):
    
    servicos = models.CharField('servicos', max_length=10, choices=SERVICOS)
    coleta = models.CharField('coleta', max_length=100)
    entrega = models.CharField('entrega', max_length=100)
    time = models.CharField('time', blank=True, max_length=20)
    distancia = models.DecimalField('distancia', blank=True, max_digits=15, decimal_places=2)
    veiculo = models.CharField('veiculo', max_length=10, choices=VEICULO)
    valor = models.DecimalField('valor', blank=True, max_digits=15, decimal_places=2)
    status = models.CharField('status', max_length=15,
                              blank=True, null=True, choices=STATUS)

    class Meta:
        ordering = ['id']

    def __str__(self):
        
        return self.servicos
    

# modelo de solicitação de serviços    
class Sol_Servicos(models.Model):
   
    servicos = models.CharField('servicos', max_length=10, choices=SERVICOS)
    coleta = models.CharField('coleta', max_length=100)
    entrega = models.CharField('entrega', max_length=100)
    time = models.CharField('time', blank=True, max_length=20)
    distancia = models.DecimalField(
        'distancia', blank=True, max_digits=15, decimal_places=2)
    veiculo = models.CharField('veiculo', max_length=10, choices=VEICULO)
    valor = models.DecimalField(
        'valor', blank=True, max_digits=15, decimal_places=2)
    status = models.CharField('status', max_length=15,
                              blank=True, null=True, choices=STATUS)

    class Meta:
        ordering = ['id']

    def __str__(self):

        return self.servicos

appUber/forms.py
from django import forms

from .models import Servicos, Sol_Servicos


class Formendereço(forms.ModelForm):
    class Meta:
        model = Servicos
        fields = ['servicos', 'coleta', 'entrega', 'veiculo', 'status']


class Formsolicitação(forms.ModelForm):
    class Meta:
        model = Sol_Servicos
        fields = ['servicos', 'coleta', 'entrega', 'time', 'distancia',  'veiculo', 'valor', 'status']

appUber/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .forms import Formendereço, Formsolicitação
from django.contrib import messages
from .models import Servicos, Sol_Servicos
from .coordenadas import coord, distancia, valor, Servidor, momento, decimalconverter
from django.contrib.auth.models import User, Group
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


@login_required(login_url='usuarios/login/')
def Index(request):

    if str(request.method) == 'POST':
        form = Formendereço(request.POST, request.FILES)
        if form.is_valid():
            # form.save()
            context = {
                'form': form
            }

            list1 = []
            coleta = context['form']['coleta'].value()
            entrega = context['form']['entrega'].value()
            veiculo = context['form']['veiculo'].value()
            list1.append(coleta)
            list1.append(entrega)

            coordenadas = []

            for i in range(len(list1)):

                c = coord(list1[i-1])
                coordenadas.append(c)
            dist = distancia(coordenadas)

            value = valor(dist, veiculo)

            # salvando dados acrescentando distancia no bd Servicos.
            b = Servicos(servicos=context['form']['servicos'].value(), coleta=context['form']['coleta'].value(
            ), entrega=context['form']['entrega'].value(), time=momento(), veiculo=context['form']['veiculo'].value(), distancia=dist, valor=value, status='Waiting')

            b.save()

            return redirect('servicos')

        else:
            print('erro')
            messages.success(request, 'erro')

    return render(request, 'index.html')


@login_required(login_url='usuarios/login/')
def Servico(request):
    corrida = Servicos.objects.all()
    corrida = corrida[len(corrida)-1]

    context = {
        'servicos': corrida.servicos,
        'coleta': corrida.coleta,
        'entrega': corrida.entrega,
        'veiculo': corrida.veiculo,
        'distancia': corrida.distancia,
        'valor': corrida.valor
    }

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':

        coleta = request.POST.get("coleta2")
        entrega = request.POST.get("entrega2")
        veiculo = request.POST.get("veiculo2")

        distancia = request.POST.get("valor_distancia")

        distancia2 = decimalconverter(distancia)

        valor = request.POST.get("valor")
        valor2 = decimalconverter(valor)

        b = Sol_Servicos(servicos=corrida.servicos, coleta=coleta, entrega=entrega, time=momento(
        ), veiculo=veiculo, distancia=distancia2, valor=valor2, status='Pending')

        b.save()
        return JsonResponse({"message": "success"})
        # return redirect('Solicite')

    return render(request, 'servicos.html', context)


class Solicite(TemplateView):

    template_name = 'solicite.html'

appUber/templates/b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

appUber/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% load static %}

{% block content %}

<nav class="navbar navbar-default">
    <a class="navbar-brand" href="#">Django Uber</a>

    <div id="navbarNav">
        <ul class="nav me-auto">

            <li>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">

    {% if user.is_anonymous %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12 index" align="center">
                <h1>Django Delivery</h1>
                <br>
                <h4>Você não estar logado</h4>
                <br><br>
                <a class="btn btn-primary" href="{% url 'login' %}">Fazer Login</a>
            </div>
        </div>
    </div>
    {% elif user.tipo == 'usuario' or user.is_staff == True %}
    <br>
    <div class="alert alert-primary" role="alert">
        seja bem vindo {{ user.username }}!
    </div>
    <div id="servicos" class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <div class="col-sm-12 col-lg-12">
                    <nav class="navbar navbar-default">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                        </div>

                        <div>
                            <ul class="nav">
                                <button type="button" class="btn  btn-mostrar"
                                    onclick="Mudarestado('tabela')">Delivery</button>
                            </ul>

                        </div>

                    </nav>
                </div>
                <br><br>
                <div>
                    <h1>Dados de Localização</h1>
                </div>
                <br><br>

                <div class="col-sm-12 col-lg-12">
                    <!-- onsubmit="debug(event)" nao carrega a page -->
                    <form action="#" method="POST" autocomplete="off" enctype="multipart/form-data">
                        {%csrf_token %}
                        <div id="tabela">
                            <label for="exampleDataList" id="lable" class="form-label">Endereço de COLETA</label>
                            <div class="autocomplete-container" id="autocomplete-container" id="auto0">

                                <div class="input-container" id="auto1">
                                    <input class="form-control" type="text" name="nome" id="auto2">
                                </div>
                                <br>
                                <a type="#" class="btn btn-outline-success" onclick="carregar()" href="#">Ok</a>
                                <br>
                                <br>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_servicos">Servicos</label><select
                                                    name="servicos" class="form-select" required="" id="id_servicos">
                                                    <option value="" selected="">---------</option>

                                                    <option value="viagem">viagem</option>

                                                    <option value="delivery">delivery</option>

                                                </select>
                                            </div>
                                        </div>


                                        <div class="col-9">
                                            <label class="form-label" for="id_coleta">Coleta</label>
                                            <input type="text" name="coleta" maxlength="100" class="form-control"
                                                placeholder="Coleta" required="" id="id_coleta">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-9">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_entrega">Entrega</label><input
                                                    type="text" name="entrega" maxlength="100" class="form-control"
                                                    placeholder="Entrega" required="" id="id_entrega">
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_veiculo">Veiculo</label>
                                                <select name="veiculo" class="form-select" id="id_veiculo">
                                                    <option value="" selected="">---------</option>

                                                    <option value="moto">moto</option>

                                                    <option value="carro">carro</option>

                                                    <option value="caminhao">caminhão</option>

                                                    <option value="carreta">carreta</option>

                                                </select>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-outline-success" type="submit">Enviar</button>
                        </div>
                    </form>
                </div>
                <br>



            </div>

        </div>

        {% elif user.tipo == 'colaborador' %}
        <div class="alert alert-primary" role="alert">
            seja bem vindo {{ user.username }}!
        </div>

    </div>
</div>

{% endif %}
</div>

{% endblock %}

appUber/templates/inicio.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% load static %}

{% block content %}


<nav class="navbar navbar-default">
    <a class="navbar-brand" href="#">DjangoUber</a>

    <div id="navbarNav">
        <ul class="nav me-auto">
            <li>
                <a class="nav-item nav-link" href="#">{{user.username}}</a>
            </li>
            <li>
                <a class="nav-item nav-link" href="{% url 'login' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">

    {% if user.is_anonymous %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12 index" align="center">
                <h1>Controle de Estoque</h1>
                <br>
                <h4>Você não estar logado</h4>
                <br><br>
                <a class="btn btn-primary" href="{% url 'login' %}">Fazer Login</a>
            </div>
        </div>
    </div>
    {% else %}
    <br>
    <div class="alert alert-primary" role="alert">
        seja bem vindo {{ user.username }}!
    </div>
    <div id="servicos" class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <div class="col-sm-12 col-lg-12">
                    <nav class="navbar navbar-default">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                        </div>

                        <div>
                            <ul class="nav">
                                <button type="button" class="btn  btn-mostrar"
                                    onclick="Mudarestado('tabela')">Delivery</button>
                            </ul>

                        </div>

                    </nav>
                </div>
                <br><br>
                <div>
                    <h1>Dados de Localização</h1>
                </div>
                <br><br>

                <div class="col-sm-12 col-lg-12">
                     <!-- onsubmit="debug(event)" nao carrega a page -->
                    <form action="#" method="POST" autocomplete="off" enctype="multipart/form-data">
                        {%csrf_token %}
                        <div id="tabela">
                            <label for="exampleDataList" id="lable" class="form-label">Endereço de COLETA</label>
                            <div class="autocomplete-container" id="autocomplete-container" id="auto0">

                                <div class="input-container" id="auto1">
                                    <input class="form-control" type="text" name="nome" id="auto2">
                                </div>
                                <br>
                                <a type="#" class="btn btn-outline-success" onclick="carregar()" href="#">Ok</a>
                                <br>
                                <br>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-3"> 
                                            <div class="mb-3">
                                                <label class="form-label" for="id_servicos">Servicos</label><select
                                                    name="servicos" class="form-select" required="" id="id_servicos">
                                                    <option value="" selected="">---------</option>

                                                    <option value="viagem">viagem</option>

                                                    <option value="delivery">delivery</option>

                                                </select>
                                            </div>
                                        </div>


                                        <div class="col-9">
                                            <label class="form-label" for="id_coleta">Coleta</label>
                                            <input type="text"
                                                name="coleta" maxlength="100" class="form-control" placeholder="Coleta"
                                                required="" id="id_coleta">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-9">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_entrega">Entrega</label><input
                                                    type="text" name="entrega" maxlength="100" class="form-control"
                                                    placeholder="Entrega" required="" id="id_entrega">
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label class="form-label" for="id_veiculo">Veiculo</label>
                                                <select name="veiculo" class="form-select" id="id_veiculo">
                                                    <option value="" selected="">---------</option>

                                                    <option value="moto">moto</option>

                                                    <option value="carro">carro</option>

                                                    <option value="caminhao">caminhão</option>

                                                    <option value="carreta">carreta</option>

                                                </select>
                                            </div>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-outline-success" type="submit">Enviar</button>
                        </div>
                </div>
                <br>


                </form>

            </div>

        </div>


    </div>
</div>

{% endif %}
</div>

{% endblock %}

appUber/templates/servicos.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}


<div id="solicite" class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-12">
            <div class="col-sm-12 col-lg-12">
                <nav class="navbar navbar-default">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                    </div>

                    <div>
                        <div class="mb-3">
                            <label class="form-label" for="veiculo">Veículo</label>
                            <select name="veículo" class="form-select campo" required="" id="serv_veiculos"
                                onChange="valor()">
                                <option value="" selected="">---------</option>

                                <option value="1">Moto</option>

                                <option value="2">carro</option>

                                <option value="3">caminhão</option>

                                <option value="4">carreta</option>

                            </select>
                        </div>
                    </div>

                </nav>
            </div>
            <br><br>
            <div>
                <h1>Dados de Serviço</h1>
            </div>
            <br><br>

            <div class="col-sm-12 col-lg-12">
                <div class="container">
                    <div class="row">

                        <form id = "form" action="{% url 'servicos'  %}" method="POST" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
                            <div class="container">
                                <div class="row">

                                    <div class="col-6">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_coleta">Coleta</label>
                                            <input type="text" name="coleta2" value="{{coleta}}" maxlength="100"
                                                class="form-control" placeholder="Coleta" id="id_coleta2" readonly>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_coleta">Entrega</label>
                                            <input type="text" name="entrega2" value="{{entrega}}" maxlength="100"
                                                class="form-control" placeholder="Entrega" id="id_entrega2" readonly>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                    <div class="col-4">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_coleta">Veículo</label>
                                            <input type="text" name="veiculo2" value="{{veiculo}}" maxlength="100"
                                                class="form-control" placeholder="Veículo" id="id_veiculo2" readonly>
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_coleta">Distancia(percurso)</label>
                                            <input type="text" name="valor_distancia" value="{{distancia}}"
                                                maxlength="100" class="form-control" placeholder="Distancia"
                                                id="id_distancia2" readonly>
                                        </div>
                                    </div>


                                    <div class="col-4">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_coleta">Valor do Serviço</label>
                                            <input type="text" name="valor" value="{{valor}}" maxlength="100"
                                                class="form-control" placeholder="valor" id="id_valor2" readonly>
                                        </div>
                                    </div>

                                </div>
                                <br>

                            </div>
                            <button type="submit" class="btn btn-primary btnSave" data-toggle="modal" data-target="#vendedorModal">Solicitar
                                Delivery</button>
                        </form>

                    </div>
                </div>
            </div>

        </div>
       
    </div>
    {% include "solicite.html" %}
</div>
<!-- Button trigger modal -->

<script>
    $("#form").on("submit", function (e) {
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);

        var valid = true;
        $('#form input').each(function () {
            let $this = $(this);

            if (!$this.val()) {
                valid = false;
                alert('peencha os campos')
                //$this.parents('.validate').find('.mySpan').text('The ' + $this.attr('name').replace(/[\_]+/g, ' ') + ' field is required');
            }
        });

        if (valid) {
            $(".btnSave").text('Solicitação de serviço enviada...').attr('disabled', true);
            let data = $this.serialize();
            $.ajax({
                url: $this.attr("action"),
                type: "POST",
                data: data,
                dataType: "json",
                success: function (resp) {
                    if (resp.message == "success") {
                        
                        $("#form")[0].reset();
                    }
                    else {
                        alert(resp.message);
                    }
                    $(".btnSave").text('Aguarde sua solicitação ser aceita...').attr('disabled', false);
                },
                error: function (resp) {
                    console.log("Something went wrong");
                    $(".btnSave").text('Save').attr('disabled', false);
                }
            });
        }
        return false;
    });
</script>

{% endblock %}

appUber/templates/solicite.html
{% load django_bootstrap5 %}

<div class="modal fade" id="Solicite" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Solicitação</h5>
              
            </div>
            Solicitação enviada, aguardando resposta...
        </div>
    </div>
</div>

appUber/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default justify-content-end">
            <div class="nav">
                <a class="navbar-brand" href="{% url 'profile' %}">Profile</a>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <h3>Serviços</h3>
                </div>
                <div class="offset-6 col-2">
                    <h3>Actions</h3>
                </div>
            </div>
        </div>
        <br><br>
        <div class="col-4">
            <form id="my-form" action="#" method="POST" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% comment %} <input type="hidden" name="csrfmiddlewaretoken"
                    value="SmcsBE8oXoFdegQAvpWZ7McKo1HJa0yvE5nYxgrq1r4d6b5wlhlBHJfaBZOOtrid">
                <div class="mb-3">
                    <label class="form-label" for="id_servicos">Servicos</label>
                    <select name="servicos" class="form-select" required="" id="id_servicos">
                        <option value="">---------</option>

                        <option value="viagem">viagem</option>

                        <option value="delivery" selected="">delivery</option>

                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_coleta">Coleta</label>
                    <input type="text" name="coleta" value="{{servico.coleta}}" maxlength="100" class="form-control"
                        placeholder="Coleta" required="" id="id_coleta">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_entrega">Entrega</label>
                    <input type="text" name="entrega" value="{{servico.entrega}}" maxlength="100" class="form-control"
                        placeholder="Entrega" required="" id="id_entrega">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_veiculo">Veiculo</label>
                    <select name="veiculo" class="form-select" required="" id="id_veiculo">
                        <option value="">---------</option>

                        <option value="moto">moto</option>

                        <option value="carro">carro</option>

                        <option value="caminhao">caminhão</option>

                        <option value="carreta">carreta</option>

                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_status">Status</label>
                    <select name="status" class="form-select" value="" required="" id="id_status">
                        <option value="">---------</option>

                        <option value="Pending">Pending</option>

                        <option value="accepted">accepted</option>

                    </select>
                </div> {% endcomment %}

            </form>
        </div>
        <div class="offset-6 col-2">

            <div class="form-group">
                <button form="my-form" type="submit" class="btn btn-secondary">Update</button>
            </div>
            <br>
            <div class="form-group">
                <a href="delete/{{servico.id}}" form="my-form" type="submit" class="btn btn-danger">Delete</a>
            </div>

        </div>


        <!-- {% if messages %}
        {%for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{message}}
        </div>
        {%endfor%}
        {% endif %} -->

    </div>
</div>
{% endblock %}